# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 51002b28386ce676ddbf0d9ad0fd670211f874d3d33ed1e823dbabcf32eb71b03a433445a29aa154c482e59133a957e990485c6745ecaf0f31087fd218ed6b75

test:
  secret_key_base: ea7534865314722ac289393496bd3746caba5d3a0ca838272bd4f5a733fbbc4db27e8255ffef34c105a48ee32df585c0038c951becde021bc85a1e74ae04f646

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
